version: "3.8"

services:
  # 1. Database chính
  postgres:
    image: postgres:16-alpine # Bản alpine cho nhẹ
    container_name: hotel_postgres
    restart: always
    environment:
      POSTGRES_USER: thanhhoa
      POSTGRES_PASSWORD: 135213079819
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis cho Cache & Queue
  redis:
    image: redis:alpine
    container_name: hotel_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
